// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { defineMcp } from "npm:@lovable.dev/mcp-js@0.20.0";

// src/lib/mcp/tools/search-recipes.ts
import { createClient } from "npm:@supabase/supabase-js@^2.105.4";
import { defineTool } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z } from "npm:zod@^4.4.3";
function sb() {
  return createClient(
    process.env.SUPABASE_URL,
    process.env.SUPABASE_PUBLISHABLE_KEY ?? process.env.SUPABASE_ANON_KEY,
    { auth: { persistSession: false, autoRefreshToken: false } }
  );
}
var search_recipes_default = defineTool({
  name: "search_recipes",
  title: "Search recipes",
  description: "Search published recipes in Un Cuchar\xF3n de Amor by name, ingredient, or category. Returns up to 20 matches.",
  inputSchema: {
    query: z.string().optional().describe("Text to match against recipe name or ingredients."),
    category: z.string().optional().describe("Optional category filter."),
    limit: z.number().int().min(1).max(20).optional().describe("Max results (default 10).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ query, category, limit }) => {
    let q = sb().from("recipes_staging").select("id,name,category,time,servings,image_url").eq("status", "published").order("created_at", { ascending: false }).limit(limit ?? 10);
    if (category) q = q.ilike("category", `%${category}%`);
    if (query) q = q.or(`name.ilike.%${query}%,ingredients.ilike.%${query}%`);
    const { data, error } = await q;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? []) }],
      structuredContent: { recipes: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/get-recipe.ts
import { createClient as createClient2 } from "npm:@supabase/supabase-js@^2.105.4";
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z as z2 } from "npm:zod@^4.4.3";
function sb2() {
  return createClient2(
    process.env.SUPABASE_URL,
    process.env.SUPABASE_PUBLISHABLE_KEY ?? process.env.SUPABASE_ANON_KEY,
    { auth: { persistSession: false, autoRefreshToken: false } }
  );
}
var get_recipe_default = defineTool2({
  name: "get_recipe",
  title: "Get recipe",
  description: "Fetch the full details of a published recipe by its id.",
  inputSchema: {
    id: z2.string().min(1).describe("Recipe id.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ id }) => {
    const { data, error } = await sb2().from("recipes_staging").select("*").eq("id", id).eq("status", "published").maybeSingle();
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    if (!data) return { content: [{ type: "text", text: "Recipe not found" }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data) }],
      structuredContent: { recipe: data }
    };
  }
});

// src/lib/mcp/tools/generate-recipe-idea.ts
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z as z3 } from "npm:zod@^4.4.3";
var generate_recipe_idea_default = defineTool3({
  name: "generate_recipe_idea",
  title: "Generate recipe idea",
  description: "Generate a new, gentle-on-the-body recipe idea from an ingredient and/or mood using Un Cuchar\xF3n de Amor's AI chef.",
  inputSchema: {
    ingredient: z3.string().optional().describe("Main ingredient available at home."),
    mood: z3.enum(["liviano", "confort", "rapido", "dulce", "sinculpa", "sorpresa"]).optional().describe("How the user's body feels today."),
    prefs: z3.array(z3.string()).optional().describe("Dietary preferences: airfryer, rapido, singluten, sinlacteos, proteina, veggie.")
  },
  annotations: { readOnlyHint: true, openWorldHint: true },
  handler: async ({ ingredient, mood, prefs }) => {
    const url = `${process.env.SUPABASE_URL}/functions/v1/generate-recipe`;
    const resp = await fetch(url, {
      method: "POST",
      headers: {
        "Content-Type": "application/json",
        apikey: process.env.SUPABASE_PUBLISHABLE_KEY ?? process.env.SUPABASE_ANON_KEY,
        Authorization: `Bearer ${process.env.SUPABASE_PUBLISHABLE_KEY ?? process.env.SUPABASE_ANON_KEY}`
      },
      body: JSON.stringify({ ingredient: ingredient ?? "", mood: mood ?? null, prefs: prefs ?? [] })
    });
    const data = await resp.json().catch(() => ({}));
    if (!resp.ok || data?.error) {
      return {
        content: [{ type: "text", text: data?.error ?? `Error ${resp.status}` }],
        isError: true
      };
    }
    return {
      content: [{ type: "text", text: JSON.stringify(data.recipe) }],
      structuredContent: { recipe: data.recipe }
    };
  }
});

// src/lib/mcp/index.ts
var mcp_default = defineMcp({
  name: "cucharon-de-amor-mcp",
  title: "Un Cuchar\xF3n de Amor",
  version: "0.1.0",
  instructions: "Tools for Un Cuchar\xF3n de Amor, a gentle-on-the-body Spanish recipe app. Use `search_recipes` to browse the published recipe library, `get_recipe` to fetch full ingredients and steps, and `generate_recipe_idea` to create a new recipe from an ingredient or mood.",
  tools: [search_recipes_default, get_recipe_default, generate_recipe_idea_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.20.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
